export enum BilgeState {
  DRY = 'DRY',
  SOME_WATER_NOT_EMPTIED = 'SOME WATER AND NOT EMPTIED',
  SOME_WATER_AND_EMPTIED = 'SOME WATER AND EMPTIED',
  FULL_NOT_EMPTIED = 'FULL OF WATER AND NOT EMPTIED',
  FULL_AND_EMPTIED = 'FULL OF WATER AND EMPTIED',
  DID_NOT_CHECK = 'DID NOT CHECK',
  NOT_APPLICABLE = 'NOT APPLICABLE',
}
