export enum VhfState {
  DEAD_BATTERY = 'DEAD BATTERY',
  DID_NOT_CHECK = 'DID NOT CHECK',
  NOT_WORKING = 'NOT WORKING',
  WORKING_16 = 'WORKING CHANNEL 16',
  WORKING_LOW_BATTERY = 'WORKING WITH LOW BATTERIES',
  NOT_APPLICABLE = 'NOT APPLICABLE',
}
