# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.1
  heroku: circleci/heroku@1.2

jobs:
  "Build and deploy":
    docker:
      - image: cimg/node:lts
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - heroku/install
      - setup_remote_docker:
          version: docker24
      - run: docker --version
      - run: chmod +x ./build-docker.sh
      - run: 
          name: Build docker image
          command: docker build -t bsac/sail-manager:$CIRCLE_SHA1 .
      - run:
          name: Push to DockerHub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker image push bsac/sail-manager:$CIRCLE_SHA1

      - heroku/push-docker-image:
          process-types: web
      - heroku/release-docker-image:
          process-types: web

workflows:
  Build-And-Publish:
    jobs:
      - "Build and deploy":
          filters:
            branches:
              only:
                - master
