export enum UserAccessFields {
  CreateBoat = 'createBoat',
  CreateChallenge = 'createChallenge',
  CreateClinic = 'createClinic',
  CreateSail = 'createSail',
  CreateSailRequest = 'createSailRequest',
  DeletePictures = 'deletePictures',
  DownloadSails = 'downloadSails',
  DownloadSailRequests = 'downloadSailRequests',
  EditBoat = 'editBoat',
  EditChallenge = 'editChallenge',
  EditClinic = 'editClinic',
  EditMaintentanceRequest = 'editMaintenanceRequest',
  EditSail = 'editSail',
  EditSailRequest = 'editSailRequest',
  EditUserAccess = 'editUserAccess',
  EditUserProfile = 'editUserProfile',
  JudgeChallenge = 'judgeChallenge',
  ResolveMaintenanceRequest = 'resolveMaintenanceRequest',
  ViewChallengeAccomplishments = 'viewChallengeAccomplishments',
  ViewUserSails = 'viewUserSails',
}
