# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 16-buster
    command: sleep infinity
    volumes:
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - sail_manager:/workspace

  redis:
    image: redis
    command: redis-server
    restart: always

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081

  db:
    image: postgres:14.13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password

  dbeaver:
    image: dbeaver/cloudbeaver:latest
    restart: always
    ports:
      - 8080:8978
  
volumes:
  sail_manager:
